### ISSUE TITLE
CT tried to removeListener on something that wasn't a listener

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/buoyancy-basics#17]
```
buoyancy-basics : phet-io-state-fuzz : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/phet-io-wrappers/state/?sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717752560430%7D
ERROR: Assertion failed: tried to removeListener on something that wasn't a listener
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/assert/js/assert.js:43:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/assert/js/assert.js:43:13)
    at  (TinyEmitter.ts:263:14)
    at removeListener (TinyProperty.ts:150:9)
    at unlink (ReadOnlyProperty.ts:466:22)
    at unlink (DynamicProperty.ts:286:54)
    at call (Disposable.ts:50:21)
    at dispose (DensityAccordionBox.ts:65:19)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (ReadoutListAccordionBox.ts:105:24)
    at setReadoutItems (BuoyancyCompareScreenView.ts:154:26)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:352:22)
    at _notifyListeners (ReadOnlyProperty.ts:400:46)
    at listener (PropertyStateHandler.ts:278:40)
    at attemptToApplyPhases (PropertyStateHandler.ts:198:11)
    at undeferAndNotifyProperties (PropertyStateHandler.ts:91:11)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Emitter.ts:64:21)
    at emit (PhetioStateEngine.ts:265:24)
    at setState (PhetioStateEngine.ts:282:9)
    at setFullState (phetioEngine.ts:1158:33)
    at apply (phetioCommandProcessor.ts:429:50)
    at process (phetioCommandProcessor.ts:303:35)
    at getReturn (phetioCommandProcessor.ts:311:17)
    at map (phetioCommandProcessor.ts:301:29)
    at processCommands (phetioCommandProcessor.ts:242:34)
    at addEventListener (phetioCommandProcessor.ts:197:11)
    at  (phetioCommandProcessor.ts:545:31)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1717751755060%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dbuoyancy-basics%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717752560430%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1717751755060%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dbuoyancy-basics%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717752560430%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/phet-io-wrappers/state/?sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717752560430%7D
[ATTACHED] 
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/buoyancy-basics/buoyancy-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717752560430%7D&frameTitle=source
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/buoyancy-basics/buoyancy-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717752560430%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  tried to removeListener on something that wasn't a listener
[CONSOLE] Debug info: {
  "seed": 0.7056135817160176,
  "currentScreenName": "CompareScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "PopupParentNode: PreferencesDialog"
  ]
}
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[PAGE ERROR] Error: Assertion failed: tried to removeListener on something that wasn't a listener

id: "Sparky Node Firefox"
Snapshot from 6/7/2024, 3:15:55 AM

----------------------------------

buoyancy-basics : phet-io-state-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/phet-io-wrappers/state/?sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717772147255%7D
ERROR: Assertion failed: tried to removeListener on something that wasn't a listener
STACK: Error: Assertion failed: tried to removeListener on something that wasn't a listener
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/assert/js/assert.js:43:13)
    at assert (TinyEmitter.ts:263:6)
    at removeListener (TinyProperty.ts:150:9)
    at unlink (ReadOnlyProperty.ts:466:22)
    at unlink (DynamicProperty.ts:247:38)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:352:22)
    at _notifyListeners (ReadOnlyProperty.ts:400:46)
    at listener (PropertyStateHandler.ts:278:40)
    at attemptToApplyPhases (PropertyStateHandler.ts:198:11)
    at undeferAndNotifyProperties (PropertyStateHandler.ts:91:11)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Emitter.ts:64:21)
    at emit (PhetioStateEngine.ts:265:24)
    at setState (PhetioStateEngine.ts:282:9)
    at setFullState (phetioEngine.ts:1158:33)
    at apply (phetioCommandProcessor.ts:429:50)
    at process (phetioCommandProcessor.ts:303:35)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1717751755060%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dbuoyancy-basics%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717772147255%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1717751755060%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dbuoyancy-basics%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717772147255%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/phet-io-wrappers/state/?sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717772147255%7D
[ATTACHED] 
[NAVIGATED] about:blank
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/buoyancy-basics/buoyancy-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717772147255%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/buoyancy-basics/buoyancy-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1717751755060%22%2C%22timestamp%22%3A1717772147255%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  tried to removeListener on something that wasn't a listener
[CONSOLE] Debug info: {
  "seed": 0.3507352057146633,
  "currentScreenName": "ExploreScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "PopupParentNode: PreferencesDialog",
    "PopupParentNode: AboutDialog"
  ]
}
[PAGE ERROR] Error: Error: Assertion failed: tried to removeListener on something that wasn't a listener
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/assert/js/assert.js:43:13)
    at TinyProperty.removeListener (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/TinyEmitter.js:222:7)
    at TinyProperty.unlink (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/TinyProperty.js:134:10)
    at LocalizedStringProperty.unlink (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/ReadOnlyProperty.js:371:23)
    at DynamicProperty.onPropertyChange (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/DynamicProperty.js:195:37)
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/ReadOnlyProperty.js:264:23)
    at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/ReadOnlyProperty.js:309:47)
    at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/PropertyStateHandler.js:224:41)
    at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/PropertyStateHandler.js:153:12)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/PropertyStateHandler.js:57:12
    at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/TinyEmitter.js:161:14)
    at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/axon/js/Emitter.js:52:22)
    at PhetioStateEngine.setState (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/phet-io/js/PhetioStateEngine.js:247:25)
    at PhetioStateEngine.setFullState (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/phet-io/js/PhetioStateEngine.js:264:10)
    at PhetioEngine.implementation (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/phet-io/js/phetioEngine.js:989:34)
    at PhetioCommandProcessor.process (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:312:51)
    at getReturn (http://128.138.93.172/continuous-testing/ct-snapshots/1717751755060/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:181:29)
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 6/7/2024, 3:15:55 AM
```

**Comment by zepumph** [comment]
Thanks, this is triggered by https://github.com/phetsims/density-buoyancy-common/issues/163

**Comment by samreid** [comment]
Solved in https://github.com/phetsims/density-buoyancy-common/issues/163, @zepumph will review CT in an hour to see if it is clear.

**Comment by zepumph** [comment]
Not clear enough yet. I'll need to take a look in a day or two.

**Comment by AgustinVallejo** [comment]
Linking https://github.com/phetsims/buoyancy/issues/67 as the best paper trail for this.

**Comment by samreid** [comment]
@zepumph and I fixed this and it has been clear for 10+ columns on CT. Thanks everyone, closing.
